[project]
name = "get-wrapped"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
]

[build-system]
requires = ["uv_build >= 0.9.17, <0.10.0"]
build-backend = "uv_build"
